// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package todos

import (
	"github.com/shipyardapp/blog-wire/src/config"
	"github.com/shipyardapp/blog-wire/src/domain/todo/todoservice"
	"github.com/shipyardapp/blog-wire/src/domain/user/userservice"
	"github.com/shipyardapp/blog-wire/src/infra/server"
	"github.com/shipyardapp/blog-wire/src/infra/somerealapm"
	"github.com/shipyardapp/blog-wire/src/infra/sqldb"
	"github.com/shipyardapp/blog-wire/src/infra/todorepo"
	"github.com/shipyardapp/blog-wire/src/infra/userrepo"
	"github.com/shipyardapp/blog-wire/src/todos/handler/api"
	"log"
)

// Injectors from wire.go:

func InitializeApp(enver config.Enver, logger *log.Logger) (*App, error) {
	sqldbConfig, err := sqldb.NewConfig(enver)
	if err != nil {
		return nil, err
	}
	db, err := sqldb.New(sqldbConfig)
	if err != nil {
		return nil, err
	}
	somerealapmConfig, err := somerealapm.NewConfig(enver)
	if err != nil {
		return nil, err
	}
	apm, err := somerealapm.New(somerealapmConfig)
	if err != nil {
		return nil, err
	}
	serverConfig, err := server.NewConfig(enver)
	if err != nil {
		return nil, err
	}
	apiConfig, err := api.NewConfig(enver)
	if err != nil {
		return nil, err
	}
	userserviceConfig, err := userservice.NewConfig(enver)
	if err != nil {
		return nil, err
	}
	repo := userrepo.New(db)
	service := userservice.New(userserviceConfig, repo)
	todoserviceConfig, err := todoservice.NewConfig(enver)
	if err != nil {
		return nil, err
	}
	todorepoRepo := todorepo.New(db)
	todoserviceService := todoservice.New(todoserviceConfig, todorepoRepo)
	apiAPI := api.New(apiConfig, apm, logger, service, todoserviceService)
	serverServer := server.New(serverConfig, apiAPI)
	app := New(db, apm, serverServer)
	return app, nil
}
